const express = require('express');
const router = express.Router();
const ctrl = require('./releases.controller');
const { authenticateToken, authorizeRoles } = require('../../middleware/auth.middleware');

// ── Public Utility ──────────────────────────────────────────────────────────
// Game info lookup is a public utility (no auth needed)
router.get('/game-info/:gameId', ctrl.gameInfo.bind(ctrl));
router.get('/verify-token', ctrl.verifyToken.bind(ctrl));

// ── Secure Script Delivery (Two-Stage Loading — Stage 2) ───────────────────
// This endpoint handles authenticated, encrypted delivery of real script content.
// Called internally by the Roblox-side gatekeeper script generated by Stage 1 (/releases/:prefix).
// Requires: x-valinc-handshake: 'TRUE', User-Agent: 'RobloxApp', valid key + HWID.
router.get('/secure-load/:prefix', ctrl.secureLoader.bind(ctrl));

// ── Authenticated CRUD (require JWT + owner/developer role) ─────────────────
router.use(authenticateToken);
router.use(authorizeRoles('owner', 'developer'));

router.post('/', ctrl.create.bind(ctrl));
router.get('/', ctrl.list.bind(ctrl));
router.get('/:id', ctrl.getById.bind(ctrl));
router.patch('/:id', ctrl.update.bind(ctrl));
router.delete('/:id', ctrl.delete.bind(ctrl));

module.exports = router;
